# Set the base image to use
FROM gcc:latest
# Copy the C program into the container
COPY NFLCombos.c .
# Compile the C program
RUN gcc -o NFLCombos NFLCombos.c
# Set the command to run when the container starts
CMD ["./NFLCombos"]